/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;
import java.util.Scanner;

public class App {

    public static boolean checker(String w) {

        if (w.length() == 0 || w.length() == 1) {
            return true;

        }// end if statement

        for( int i = 0; i < w.length(); i++){

            if(w.charAt(i) == w.charAt((w.length() - 1))) {
                return true;

            }

        }

        return false;
    }

    public static void main(String[] args) {

        System.out.println("Enter a Palindrome");
        Scanner string = new Scanner(System.in);

        String word = string.nextLine();

        checker(word);

        if(checker(word)){
            System.out.println(word + ": true");
        }else{
            System.out.println(word + ": false");
        }


    }// end main

}// end class
